#lang aws-lambda-serverless
service: test

provider:
  name: aws
  runtime: provided
  memorySize: 128
  timeout: 1

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:488514468674:layer:bootstrap:2 # Allowed all accounts!
